#!/bin/bash

#manual source deployment script
# OBS: requires you to be authenticated with the azure CLI


cd src

# remove all "garbage" we don't want in our deployment zip, since azure will do it's own compilation
rm -r */bin
rm -r */obj
rm */*.csv
rm testzip.zip
# remove any existing solution file for this folder ,autogenerated by vsc or another IDE, since it will fuck things up
rm src.sln

# create the source deployment zip
zip -r testzip.zip .

# and deploy
az webapp deploy --resource-group toej_rg_4712 --name bdsagroup26chirpremotedb --src-path testzip.zip