# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .Net Test
on: [ push, workflow_call, workflow_dispatch ]

jobs:
  setup-dotnet: 
    name: Setup dotnet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
  
  define-matrix: 
    name: Define Matrix
    runs-on: ubuntu-latest 
    outputs: 
      dirs: ${{ steps.dirs.outputs.dirs }}

    steps:
    - name: List Dirs
      id: dirs
      run: |
        echo ls 
        dirs=($(ls ./tests/* -d)) 

        out="["
        for dir in "${dirs[@]}";
        do
          out+=\"$dir\",
        done;

        # replace final , with ]
        out="dirs=${out%?}]" #prints out without the last character, then appends ]

        echo $out >> "$GITHUB_OUTPUT"
        echo ouput: $out

  test:
    name: Test
    needs: [setup-dotnet, define-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dirs: ${{ fromJSON(needs.define-matrix.outputs.dirs) }}
    steps: 
    - name: Test
      shell: bash
      run: |
        dotnet test ${{ matrix.dirs }}





