# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .Net Test
on: [ push, workflow_call ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Test
      shell: bash
      run: |
        for dir in tests/*; do
            if [ -d "$dir" ]; then
                dotnet test "$dir"
            fi
        done