# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .Net Test
on: [ push, workflow_call, workflow_dispatch ]

jobs:
  setup-dotnet: 
    name: Setup dotnet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
  
  setup-playwright: 
    name: Setup Playwright 
    needs: setup-dotnet
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v4
    - name: Install powershell
      uses: cakhanif/action-install-powershell@v1
    
    - name: Build UItest project 
      run: dotnet build tests/Chirp.Web.UITest 
    
    - name: Install Playwright with dependencies
      run: pwsh tests/Chirp.Web.UITest/bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Build Chirp.Web binaries 
      run: dotnet build src/Chirp.Web/ -c Debug 
    
    - name: Export Chirp.Web binaries 
      run: dotnet publish src/Chirp.Web/ -c Debug -o tests/Chirp.Web.UITest/bin/Debug/net8.0
      
  define-matrix: 
    name: Define Matrix
    runs-on: ubuntu-latest 
    outputs: 
      dirs: ${{ steps.dirs.outputs.dirs }}

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: List Dirs
      id: dirs
      shell: bash
      run: |
        dirs=($(ls tests/* -d)) 

        out="["
        for dir in "${dirs[@]}";
        do
          out+=\"$dir\",
        done;

        # replace final , with ]
        out="dirs=${out%?}]" #prints out without the last character, then appends ]

        echo $out >> "$GITHUB_OUTPUT"

  test:
    name: Test
    needs: [setup-dotnet, define-matrix, setup-playwright]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dirs: ${{ fromJSON(needs.define-matrix.outputs.dirs) }}
    steps: 
    - name: Checkout 
      uses: actions/checkout@v4
  
    - name: Test
      shell: bash
      run: |
        dotnet test ${{ matrix.dirs }}





